import type { ProcessedInvoice } from '@/lib/invoice-journal/types';

export function generateCSV(data: ProcessedInvoice): string {
  const headers = 'Date,Account,Account Code,Debit,Credit,Memo,Reference\n';
  const rows = data.journalEntries.map((entry) =>
    `${entry.date},"${escapeQuotes(entry.account)}",${entry.accountCode},${entry.debit || ''},${entry.credit || ''},"${escapeQuotes(entry.memo)}","${escapeQuotes(entry.reference)}"`
  ).join('\n');

  return headers + rows;
}

export function generateXeroCSV(data: ProcessedInvoice): string {
  const headers = '*ContactName,*InvoiceNumber,*InvoiceDate,*DueDate,Description,*Quantity,*UnitAmount,AccountCode,*TaxType\n';
  const taxType = data.invoice.vatRate > 0 ? '20% (VAT on Expenses)' : 'Tax Exempt (0%)';

  const rows = data.invoice.lineItems.map((item) =>
    `"${escapeQuotes(data.invoice.vendor)}","${escapeQuotes(data.invoice.invoiceNumber || '')}","${data.invoice.invoiceDate}","${data.invoice.dueDate || data.invoice.invoiceDate}","${escapeQuotes(item.description)}",${item.quantity || 1},${item.unitPrice || item.netAmount},"${data.analysis.accountCode}","${taxType}"`
  ).join('\n');

  return headers + rows;
}

export function generateSummary(data: ProcessedInvoice): string {
  return `INVOICE SUMMARY

From: ${data.invoice.vendor}
Date: ${data.invoice.invoiceDate}
Invoice #: ${data.invoice.invoiceNumber || 'N/A'}
Amount: £${data.invoice.total.toFixed(2)}

WHAT YOU NEED TO KNOW:
${data.analysis.explanation}

TAX TREATMENT:
Category: ${data.analysis.category}
Deductible Amount: £${data.analysis.deductibleAmount.toFixed(2)}
VAT Reclaimable: ${data.analysis.vatReclaimable ? 'Yes' : 'No'} - £${data.analysis.vatReclaimAmount.toFixed(2)}
${data.analysis.cisApplicable ? `CIS Applicable: ${data.analysis.cisRate}% deduction` : ''}

${data.analysis.warnings.length > 0 ? '\n⚠️ WARNINGS:\n' + data.analysis.warnings.map((warning) => `• ${warning}`).join('\n') : ''}

JOURNAL ENTRIES:
${data.journalEntries.map((entry) => {
  const amount = entry.debit ? `£${entry.debit.toFixed(2)}` : `£${(entry.credit || 0).toFixed(2)}`;
  const type = entry.debit ? 'DR' : 'CR';
  return `${type} ${entry.account} (${entry.accountCode}) ${amount}`;
}).join('\n')}

Generated by UtilityLab - ${new Date().toLocaleDateString('en-GB')}
`;
}

function escapeQuotes(value: string): string {
  return value.replace(/"/g, '""');
}
